const users = require('./users/users.service.js');
const messages = require('./messages/messages.service.js');
const comments = require('./comments/comments.service.js');
const notifications = require('./notifications/notifications.service.js');
const questions = require('./questions/questions.service.js');
const answers = require('./answers/answers.service.js');
const cvs = require('./cvs/cvs.service.js');
const admins = require('./admins/admins.service.js');
const specialists = require('./specialists/specialists.service.js');
const volunteers = require('./volunteers/volunteers.service.js');
const members = require('./members/members.service.js');
const uploads = require('./uploads/uploads.service.js');
const emails = require('./emails/emails.service.js');
const authmanagement = require('./authmanagement/authmanagement.service.js');
const close = require('./questions/close/close.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(messages);
  app.configure(comments);
  app.configure(notifications);
  app.configure(questions);
  app.configure(answers);
  app.configure(cvs);
  app.configure(admins);
  app.configure(specialists);
  app.configure(volunteers);
  app.configure(members);
  app.configure(uploads);
  app.configure(emails);
  app.configure(authmanagement);
  app.configure(close);
};
